name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Add your environment name here
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Secrets Are Set
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then echo "OPENAI_API_KEY is not set"; exit 1; fi
          if [ -z "$QDRANT_URL" ]; then echo "QDRANT_URL is not set"; exit 1; fi
          if [ -z "$QDRANT_KEY" ]; then echo "QDRANT_KEY is not set"; exit 1; fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_KEY: ${{ secrets.QDRANT_KEY }}

      - name: Run Streamlit app
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_KEY: ${{ secrets.QDRANT_KEY }}
        run: |
          streamlit run themepark_to_vectorDB_Only_Chat_UI.py
