name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Add your environment name here
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Debug Secrets
        run: |
          echo "OPENAI_API_KEY is ${#OPENAI_API_KEY} characters long"
          echo "QDRANT_URL is ${#QDRANT_URL} characters long"
          echo "QDRANT_KEY is ${#QDRANT_KEY} characters long"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_KEY: ${{ secrets.QDRANT_KEY }}
          
      - name: Run Streamlit app
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_KEY: ${{ secrets.QDRANT_KEY }}
        run: |
          streamlit run themepark_to_vectorDB_Only_Chat_UI.py
