name: Scheduled Task

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 2 hours. Adjust as needed.

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: production 
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need.

      - name: Install dependencies
        run: |
          pip install -r requirements.txt 

      - name: Run Python script
        env:
          MY_OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_QDRANT_URL: ${{ secrets.QDRANT_URL }}
          MY_QDRANT_KEY: ${{ secrets.QDRANT_KEY }}
        run: |
          echo "Checking environment variables..."
          echo "MY_OPENAI_KEY is ${#MY_OPENAI_KEY} characters long"
          echo "MY_QDRANT_URL is ${#MY_QDRANT_URL} characters long"
          echo "MY_QDRANT_KEY is ${#MY_QDRANT_KEY} characters long"
          streamlit run themepark_to_vectorDB_Only_Chat_UI.py
